[package]
name = "tugger-windows"
version = "0.5.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Collection of packaging primitives specific to Windows"
keywords = ["tugger", "windows"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
duct = "0.13"
glob = "0.3"
once_cell = "1.7"
semver = "0.11"

[target.'cfg(windows)'.dependencies]
find-winsdk = "0.2"
winapi = { version = "0.3", features = ["combaseapi", "knownfolders", "shlobj", "shtypes"] }

[dependencies.tugger-common]
version = "0.4.0-pre"
path = "../tugger-common"
